services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: minha_cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: troque-esta-senha
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
